### ISSUE TITLE
spam/phishing?

### ISSUE THREAD

**Issue by promptjunkie** [sspeiser/onenote-export#5]
hello...after using this I have been bombarded with spam/phishing attacks to my email address. This is the only thing I can think of that would have caused more spam/phishing attacks since I was not receiving any before using this. What does this program do with the email after signing in?

**Comment by sspeiser** [comment]
Hi thanks for your comment. As you can see in the source code the only thing the email is used for is to display it in the navbar. It is not stored anywhere or forwarded to anybody. You can do a source search: https://github.com/sspeiser/onenote-export/search?q=mail or https://github.com/sspeiser/onenote-export/search?q=email to see the only relevant source code pieces. The hosted version is published as-is from the source code repository using the gh-pages plugin. I'm very confident that this program has nothing to do with any spam or phishing.

**Comment by promptjunkie** [comment]
ok thank you for letting me know.
